name: Deploy SSL certificate to Tencent Cloud CDN
description: Deploy SSL certificate to Tencent Cloud CDN.
branding:
  icon: lock
  color: green
inputs:
  secret-id:
    description: The secretId used to authenticate with Tencent Cloud.
    required: true
  secret-key:
    description: The accessKeySecret used to authenticate with Tencent Cloud.
    required: true
  fullchain-file:
    description: The file path of the PEM fullchain certificate.
    required: true
  key-file:
    description: The file path of the PEM private key file.
    required: true
  zone-id:
    description: Enter a list of zone ID you want to deploy the certificate to.
    required: true
  zone-id-domains:
    description: Enter a list of domains you want to deploy the certificate to zone-id, in the format of `domain1 domain2`.
    required: true
runs:
  using: node20
  main: bootstrap.js
